# Generated by Django 5.1.6 on 2025-03-02 16:03

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='photo_url',
            field=models.ImageField(upload_to=events.models.event_photo_path),
        ),
    ]
