# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEventcreation():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eventcreation(self):
    self.driver.get("http://localhost:5173/")
    self.driver.set_window_size(1082, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".cta-btn").click()
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.NAME, "login").send_keys("vivekmohanraj5@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Vivek@123")
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "password").send_keys("Vivekmohanraj@5")
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".\\_navButton_1obdh_83:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_button_12z7l_1449:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_closeModalButton_12z7l_1893").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_navButton_1obdh_83:nth-child(3)").click()
    self.driver.find_element(By.ID, "header").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_ctaButton_trp07_317").click()
    self.driver.find_element(By.NAME, "event_name").click()
    self.driver.find_element(By.NAME, "event_name").send_keys("Sam\'s birthday")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_formSection_1ddv4_83:nth-child(1)").click()
    self.driver.find_element(By.NAME, "event_type").click()
    dropdown = self.driver.find_element(By.NAME, "event_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Birthday Party']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_formGroup_1ddv4_106:nth-child(5) > textarea").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_formGroup_1ddv4_106:nth-child(5) > textarea").send_keys("birthday")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_venueCard_1ddv4_699:nth-child(5) .\\_selectVenueBtn_1ddv4_776").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_submitButton_1ddv4_400").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_navButton_1obdh_83:nth-child(3)").click()
  
