# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost:5173/")
    self.driver.set_window_size(1082, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".cta-btn").click()
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.NAME, "login").send_keys("vivekmohanraj5@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Vivekmohanraj@5")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_customBtn_1g8d2_161").click()
    self.driver.close()	
