# Generated by Django 5.1.6 on 2025-03-18 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user_register', 'User Registration'), ('user_login', 'User Login'), ('event_created', 'Event Created'), ('event_approved', 'Event Approved'), ('event_rejected', 'Event Rejected'), ('payment_completed', 'Payment Completed'), ('ticket_purchased', 'Ticket Purchased'), ('coordinator_request', 'Coordinator Request')], max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
