# Generated by Django 5.1.6 on 2025-03-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_role_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coordinator_request',
            field=models.BooleanField(default=False),
        ),
    ]
