# Generated by Django 5.1.6 on 2025-04-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_coordinator_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('user', 'Normal User'), ('coordinator', 'Event Coordinator'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'Normal User'), ('coordinator', 'Event Coordinator'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
